import type { Metadata } from 'next';
import './globals.css';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import * as React from 'react';
import { ReactNode } from 'react';
import { NavDrawer } from '@src/components/NavDrawer/NavDrawer';
import TopBar from '@src/components/TopBar';
import Main from '@src/components/Main';
import DefaultTheme from '@src/components/Theme';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <head/>
      <body>
        <ThemeProvider theme={DefaultTheme}>
          <Box sx={{ display: 'flex' }}>
            <CssBaseline/>
            <TopBar/>
            <NavDrawer/>
            <Main>
              {children}
            </Main>
          </Box>
        </ThemeProvider>
      </body>
    </html>
  );
};

export default RootLayout;

