import type { Metadata } from 'next';
import './globals.css';
import Box from '@mui/material/Box';
import CssBaseline from '@mui/material/CssBaseline';
import { ThemeProvider } from '@mui/material/styles';
import * as React from 'react';
import { ReactNode } from 'react';
import { NavDrawer } from '@src/components/NavDrawer/NavDrawer';
import TopBar from '@src/components/TopBar';
import Main from '@src/components/Main';
import DefaultTheme from '@src/components/Theme';
import { DrawerProvider } from '@src/contexts/DrawerContext';

export const metadata: Metadata = {
  title: "Disc Golf Media",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <head/>
      <body>
        <DrawerProvider>
          <ThemeProvider theme={DefaultTheme}>
            <Box sx={{ display: 'flex' }}>
              <CssBaseline/>
              <TopBar/>
              <NavDrawer/>
              <Main>
                {children}
              </Main>
            </Box>
          </ThemeProvider>
        </DrawerProvider>
      </body>
    </html>
  );
};

export default RootLayout;

